In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Create a variable a = pd.Series([ 100, 200, 300, 400])

a = pd.Series([100, 200, 300, 400])

In [ ]:
# print a and its data type
print(a,(type))

0    100
1    200
2    300
3    400
dtype: int64 <class 'type'>

In [ ]:
#using indexing access the element 300 from the series a.

print(a[3])

400

In [ ]:
# What are the values of index for series a?
print(a.index)                                      # I {have the changed the index to a, b, c, d }

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# Change the index to  ['a', 'b', 'c', 'd']

a.index =['a','b','c','d']
print(a)

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
# Access the value in the series with index 'd'
print(a['a'])

100

In [ ]:
# Sort the values wrt to the index and print it

print(a.sort_values())

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
print(a.sort_index())

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
# Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

b = pd.Series([800, 450, 100], index = ('e','f','g'))
print(b)

e    800
f    450
g    100
dtype: int64

In [ ]:
#Append b series at the end of a series

Jodo = pd.concat([a,b])
print(Jodo)

a    100
b    200
c    300
d    400
e    800
f    450
g    100
dtype: int64

In [ ]:
#Sort the values in descending order of a and print the index of the sorted series

Descending = a.sort_values(ascending = False)
print(a.index)

Index(['a', 'b', 'c', 'd'], dtype='object')

DATAFRAME

In [ ]:
#Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

df = pd.DataFrame([a])
print(df)

     a    b    c    d
0  100  200  300  400

In [ ]:
# What is the shape of the datafarme <br>
# (also, what does it imply?)

print(df.shape)           # {checking the shape of df and a}
print(a.shape)

(1, 4)
(4,)

In [ ]:
# print the head and tail of the dataframe. <br>
# Additional - (what does head and tali represent?)

print(df.head())  # head represents the first few rows of the data Frame
print(df.tail())  # tail represents the last few rows of the data Frame

     a    b    c    d
0  100  200  300  400
     a    b    c    d
0  100  200  300  400

In [ ]:
# Rename the column of the dataframe as 'points'
df.columns = ['Points','Points','Points','Points']
print(df)

   Points  Points  Points  Points
0     100     200     300     400

In [ ]:
# Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

Fruits = pd.Series(np.random.choice(['orange','mango','apple'],7))
print(Fruits) # { use random.choice to pick randomly}

0    orange
1     mango
2     apple
3     mango
4     apple
5     apple
6    orange
dtype: object

In [ ]:
# Change the index of fruits to the index of dataframe df

Fruits.index = ['points','points','points','points','point','points','points']
print(Fruits)

points    orange
points     mango
points     apple
points     mango
point      apple
points     apple
points    orange
dtype: object

In [ ]:
# Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
# <br>print the head of the dataframe to verify

Fruits.to_frame()

             0
points  orange
points   mango
points   apple
points   mango
point    apple
points   apple
points  orange

In [ ]:
df['fruits'] = ['apple']
print(df)

   Points  Points  Points  Points fruits
0     100     200     300     400  apple

In [ ]:
print(df.head())

   Points  Points  Points  Points fruits
0     100     200     300     400  apple

PANDAS CONCATINATION

In [ ]:
# Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

d1 = pd.DataFrame({'city':['Chandigarh','Delhi','Kanpur','Chennai','Manali'],
                          'Temperature':[15, 22, 20, 26, -2],
                          })
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

In [ ]:
# Shape of d1

print(d1.shape)

(5, 2)

In [ ]:
# Set city = d1['city']

city = d1['city']
print(city)

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

In [ ]:
# print city , what is the type of city

print(city,(type))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object <class 'type'>

In [ ]:
#Create another datafeame 'd2' where the columns are <br>
# 'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
# 'Temperature' - [24,35,36,39]

d2 = pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
                          'Temperature':[24, 35, 36, 39]})

In [ ]:
# Shape of the dataframe

print(d2.shape)

(4, 2)

In [ ]:
# merge the two dataframes together, save it in a new dataframe named 'd3'

d3 = pd.concat([d1,d2])
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

In [ ]:
# Select the part of the dataframe such that it contains cities where temp is less then or equal to 20 <br>
# How many cities are there?

kam_data = d3[d3['Temperature'] <= 20]
print(kam_data)    # There are three cities having temp <= 20

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

In [ ]:
# Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

kam_hai = d3[d3['Temperature']>=35]

print(kam_hai)

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [ ]:
d3['Union_Territory'] = (d3['city'] == 'Chandigarh') | (d3['city'] == 'Pondicherry') | (d3['city'] == 'Delhi')
print(d3)  # we use | instead of (and)

          city  Temperature  Union_Territory
0   Chandigarh           15             True
1        Delhi           22             True
2       Kanpur           20            False
3      Chennai           26            False
4       Manali           -2            False
0    Bengalaru           24            False
1   Coimbatore           35            False
2    Srirangam           36            False
3  Pondicherry           39             True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [ ]:
def c_to_f(Temperature):
   return (Temperature * 9/5) + 32
print(c_to_f(10))

50.0

In [ ]:
d3['temp_fahrenheit'] = d3['Temperature'].apply(c_to_f)
print(d3)           # To use any function in yourdataframe you have yo use .apply()

          city  Temperature  Union_Territory  temp_fahrenheit
0   Chandigarh           15             True             59.0
1        Delhi           22             True             71.6
2       Kanpur           20            False             68.0
3      Chennai           26            False             78.8
4       Manali           -2            False             28.4
0    Bengalaru           24            False             75.2
1   Coimbatore           35            False             95.0
2    Srirangam           36            False             96.8
3  Pondicherry           39             True            102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [ ]:
ut_cities = d1[(d1['city'] == 'Delhi') | (d1['city'] == 'Chandigarh') ]
print(ut_cities)

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [ ]:
high_temp = d3[d3['temp_fahrenheit'] > 90]
print(high_temp)  # d1 mein fahrenheit jaisa column hi nhi hai (check = d1.columns) baklol sala

          city  Temperature  Union_Territory  temp_fahrenheit
1   Coimbatore           35            False             95.0
2    Srirangam           36            False             96.8
3  Pondicherry           39             True            102.2

Select only the first three rows of the dataframe d1.

In [ ]:
print(d1.loc[0:2])
# starting : ending

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [ ]:
print(d3.loc[ : ])
print(d3.columns[2:4])   # to select any subset or any thing in DataFrame use .loc

          city  Temperature  Union_Territory  temp_fahrenheit
0   Chandigarh           15             True             59.0
1        Delhi           22             True             71.6
2       Kanpur           20            False             68.0
3      Chennai           26            False             78.8
4       Manali           -2            False             28.4
0    Bengalaru           24            False             75.2
1   Coimbatore           35            False             95.0
2    Srirangam           36            False             96.8
3  Pondicherry           39             True            102.2
Index(['Union_Territory', 'temp_fahrenheit'], dtype='object')

In [ ]:
data = pd.DataFrame({'State':['Uttar Pradesh','Maharashtra','Gujrat'],
                          'City':['Lucknow','Mumbai','Ahemdabad'],
                          'Temperature':[30, 45, 56]})
print(data)

           State       City  Temperature
0  Uttar Pradesh    Lucknow           30
1    Maharashtra     Mumbai           45
2         Gujrat  Ahemdabad           56

In [ ]:
data.groupby('State')['Temperature'].sum()

State
Gujrat           56
Maharashtra      45
Uttar Pradesh    30
Name: Temperature, dtype: int64

In [ ]:
data.groupby('State').count()

               City  Temperature
State
Gujrat            1            1
Maharashtra       1            1
Uttar Pradesh     1            1

In [ ]:
data.groupby('State')['Temperature'].agg(['min','max'])

               min  max
State
Gujrat          56   56
Maharashtra     45   45
Uttar Pradesh   30   30

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [ ]:
a = pd.date_range(start ='2020-01-01', end= '2020-04-01' )
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01',
               '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05',
               '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09',
               '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13',
               '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17',
               '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21',
               '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25',
               '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29',
               '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04',
               '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08',
               '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12',
               '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16',
               '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20',
               '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24',
               '2020-03-25', '2020-03-26', '2020-03-27', '2020-03-28',
               '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01'],
              dtype='datetime64[ns]', freq='D')

What is the len of a?

In [ ]:
print(len(a))

92

What is the type of a?

In [ ]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>